### ISSUE TITLE
Notice: Undefined index: eduPersonPrincipalName

### ISSUE THREAD

**Issue by thejimbirch** [SU-SWS/stanford_ssp#112]
Hi,

I'm seeing this pop up in the logs from time to time on a newly launched site.  Just a PHP Notice.  We're marking it as low priority.  CC: @zchandler 

`Notice: Undefined index: eduPersonPrincipalName in stanford_ssp_simplesamlphp_auth_existing_user() (line 123 of /code/web/modules/custom/stanford_ssp/stanford_ssp.module)`

```
#0 /code/web/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'Undefined index...', '/code/web/modul...', 123, Array)
#1 /code/web/modules/custom/stanford_ssp/stanford_ssp.module(123): _drupal_error_handler(8, 'Undefined index...', '/code/web/modul...', 123, Array)
#2 [internal function]: stanford_ssp_simplesamlphp_auth_existing_user(Array)
#3 /code/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('stanford_ssp_si...', Array)
#4 /code/web/modules/contrib/simplesamlphp_auth/src/Service/SimplesamlphpDrupalAuth.php(187): Drupal\Core\Extension\ModuleHandler->invoke('stanford_ssp', 'simplesamlphp_a...', Array)
#5 /code/web/modules/custom/stanford_ssp/src/Service/StanfordSSPDrupalAuth.php(74): Drupal\simplesamlphp_auth\Service\SimplesamlphpDrupalAuth->externalRegister('geerke')
#6 /code/web/modules/contrib/simplesamlphp_auth/src/Controller/SimplesamlphpAuthController.php(192): Drupal\stanford_ssp\Service\StanfordSSPDrupalAuth->externalLoginRegister('geerke')
#7 [internal function]: Drupal\simplesamlphp_auth\Controller\SimplesamlphpAuthController->authenticate()
#8 /code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#9 /code/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#10 /code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#11 /code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#12 /code/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#13 /code/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#14 /code/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /code/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /code/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /code/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /code/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /code/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /code/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#24 {main}
```

**Comment by pookmish** [comment]
Thanks Jim.
https://github.com/SU-SWS/stanford_ssp/pull/114
